### ISSUE TITLE
Larger default window size 

### ISSUE THREAD

**Issue by larssteenhoff** [Ravbug/UnityHubNative#10]
The default window size is cutting off some content, I propose to make the default window a bit larger as can be seen in the screenshots.
![default](https://user-images.githubusercontent.com/9589240/192236695-3f25800d-e9aa-4abb-86c7-278f0ed3ddf4.png)
![proposed](https://user-images.githubusercontent.com/9589240/192236699-eb192e21-f969-4c0a-92c4-4b9399d80557.png)

**Comment by Ravbug** [comment]
Could you PR this?

**Comment by larssteenhoff** [comment]
I'm not familiar with the source code, but I would say 800 px wide woud do the job

**Comment by larssteenhoff** [comment]
> t

The larger size percentage It's 135% compared to 100% what it's now, so a 35 percent increase in width.
Hope this helps with getting the correct sizes.

**Comment by Ravbug** [comment]
Implemented in b55517c53b458ec83fbd8b7b9569ab6ecc718373

**Comment by larssteenhoff** [comment]
> Implemented in [b55517c](https://github.com/Ravbug/UnityHubNative/commit/b55517c53b458ec83fbd8b7b9569ab6ecc718373)

Looking at the code the window seems to be smaller than before ?  I'm not sure how to make a build to test it, but would be happy to test a mac build.   
OLD  <property name="size">921,553</property> 
NEW <property name="size">800,400</property>

I think perhaps the minimum_size is the one that needs to  be made a bit larger? if that's what the window defaults to , but will need check the in build to confirm, <property name="minimum_size">560,320</property>

**Comment by Ravbug** [comment]
The old behavior was to shrink the window as much as possible without clipping any buttons. On Mac, this resulted in a window size of roughly 570x320

**Comment by larssteenhoff** [comment]
> The old behavior was to shrink the window as much as possible without clipping any buttons. On Mac, this resulted in a window size of roughly 570x320

Thanks Its good now. I found the build in Actions.

![Screenshot 2022-09-28 at 18 18 03](https://user-images.githubusercontent.com/9589240/192832736-1a8eb8f9-95e3-4e6a-8750-8f434d431b86.png)
