### ISSUE TITLE
Use it without the official unityhub

### ISSUE THREAD

**Issue by Jax0rz** [Ravbug/UnityHubNative#2]
Can I use this one without the official unityhub?

**Comment by Ravbug** [comment]
If you can normally use Unity without the official hub, then you should be able to use this launcher without it as well. However, if you installed Unity through the official hub, then as of right now you cannot remove the official hub. I believe the hub does licensing in that case, but I do not know for sure.

I am trying to figure out how to launch Editors without them also launching the hub - any insights you may have would be greatly appreciated.

**Comment by Ravbug** [comment]
UnityHubNative version 1.4 now allows you to install Unity without using the official hub. You may need to keep the official hub for licensing reasons, but all other use cases should now be covered.

**Comment by Ravbug** [comment]
If you use UnityHubNative to activate Unity installs, then you should be able to uninstall the official hub and it will stop launching. Otherwise, I don't think there is a way to prevent it.
