### ISSUE TITLE
[BUG] adding path doesn't seem to work right

### ISSUE THREAD

**Issue by laurentopia** [Ravbug/UnityHubNative#21]
picture...thousand words
<img width="521" alt="image" src="https://user-images.githubusercontent.com/26075468/196293973-855995c5-bff9-43d7-80e8-1d61dcf65a5e.png">

**Comment by Ravbug** [comment]
Can you please add repro steps?

**Comment by laurentopia** [comment]
add location
select C:\Program Files\Unity\Hub\Editor\2021.3.11f1
add location 
select C:\Program Files\Unity\Hub\Editor\2021.3.11f1

you'll get 2 instances in the top list (this bug, a small one)

then select a project and click open with then select one of the instance 
= nothing
expected: launch the editor and load the project
