### ISSUE TITLE
[BUG] UnityHubNative doesn't retain any setting.

### ISSUE THREAD

**Issue by LucaFagnoni** [Ravbug/UnityHubNative#23]
UnityHubNatve version used is 1.5
Anytime I close and reopen the application no project, installed editor version or install search path is retained.
Both Unity Hub and UnityHubnative are installed in my D:/ drive, my pc is running Windows 11 Home 21H2 build 22000.1281.

**Comment by Ravbug** [comment]
Are your projects stored on your boot drive or a different drive? 

If you want to see exactly why it's not loading the data, you can set a breakpoint in interface_derived.cpp:194 and then step through.

**Comment by LucaFagnoni** [comment]
The projects are stored in D: also (not boot drive)

I found that datapath returns an invalid path : L"\\Users\\Luca\\AppData\\Roaming\\UnityHubNative\\projects.txt"
![image](https://user-images.githubusercontent.com/23366996/204152368-776588ba-4387-4f25-9ac5-d74ea7f7683d.png)

I patched it like this and it doesn't fail the file check: L"C:\\Users\\Luca\\AppData\\Roaming\\UnityHubNative\\projects.txt"
![image](https://user-images.githubusercontent.com/23366996/204152506-3f1ee185-3eea-46ee-9a2d-aa0c42ac8215.png)
![image](https://user-images.githubusercontent.com/23366996/204152538-c867f8ea-b7a5-443e-ab9e-51fda5477015.png)

The problem now is that apparently the application  can't write to 'Roaming' folder (I created the projects.txt file myself for testing)
