### ISSUE TITLE
[BUG] Can no longer find new Unity versions to install

### ISSUE THREAD

**Issue by EddieCameron** [Ravbug/UnityHubNative#25]
**Describe the bug**
When opening the Install New Editor Version popup, no versions show up, and instead you get an `Unable to access Unity versions` popup.

**To Reproduce**
1. Go to Editor Versions tab and click on the Install New button

**Additional context**
Apparently Unity recently changed the URL to access Unity versions. (See GameCI fixing the same issue here https://github.com/game-ci/versioning-backend/pull/43)

**Comment by muveso** [comment]
same here
