### ISSUE TITLE
[BUG] Unity Hub Native doesn't save my project lists

### ISSUE THREAD

**Issue by AmpereNinja** [Ravbug/UnityHubNative#3]
I don't know how to describe my issue but when I try to add a unity project to the hub and close it after I'm done working and close it the next time you try to open it there's no projects I have to manually add my unity projects to the every time I start working. It seems like even the hub saves it on my AppData folder it doesn't load my project lists from that but just started with an empty list.
Here's the files that I've found from my UnityHubNative folder residing in my appdata folder
**Sorry for my bad english*
[projects.txt](https://github.com/Ravbug/UnityHubNative/files/7517439/projects.txt)
[editorPaths.txt](https://github.com/Ravbug/UnityHubNative/files/7517440/editorPaths.txt)
*

**Comment by Ravbug** [comment]
When you launch the app, does it warn you that it is unable to load a project path?

**Comment by AmpereNinja** [comment]
No, it always gives me a blank list when you restart the program after you add a project in the app and close it

**Comment by AmpereNinja** [comment]
Here's a video demonstrating the bug

[https://youtu.be/CoXPamwg7Io](url)

**Comment by Ravbug** [comment]
Can you please try the nightly at https://github.com/Ravbug/UnityHubNative/actions/runs/1479453524 to see if it addresses the issue?

**Comment by AmpereNinja** [comment]
Hmm seems to be working. Thanks!

**Comment by AmpereNinja** [comment]
I am going to close this issue since the bug has been patched.
