### ISSUE TITLE
Please do not remove a project from list if its not found

### ISSUE THREAD

**Issue by larssteenhoff** [Ravbug/UnityHubNative#31]
I have a Unity project on an external drive and sometimes the drive is not connected to the computer ( Then its on the laptop )
And when I open unity hub native the when the drive is not attached to open any other project on my computer it will remove the project from the list in unity hub native.

I would prefer it if the project stayed in the list and just was grayed out.  
I could then later attach the drive and the project will still be visible in the list.

Now I have to add the projects back every time and its a bit tedious.

Hope this can be added, thanks.

And if I want to remove a project I can already do that manually.

**Comment by Ravbug** [comment]
A preview implementation of this is available here, would you mind testing it? https://github.com/Ravbug/UnityHubNative/actions/runs/5038897099

**Comment by larssteenhoff** [comment]
> A preview implementation of this is available here, would you mind testing it? https://github.com/Ravbug/UnityHubNative/actions/runs/5038897099

Yes it works!

Thank you

![Screenshot 2023-05-21 at 20 31 31](https://github.com/Ravbug/UnityHubNative/assets/9589240/69bb2d93-8c3b-4ec2-94bc-e5fa2758629b)
![Screenshot 2023-05-21 at 20 28 24](https://github.com/Ravbug/UnityHubNative/assets/9589240/f5dc500b-16e7-45f4-967a-926c5cacc51c)

**Comment by Ravbug** [comment]
Shipped in 1.53.
