### ISSUE TITLE
If a project has the matching editor, just launch it without showing the popup

### ISSUE THREAD

**Issue by joonjoonjoon** [Ravbug/UnityHubNative#32]
The "open with specific editor" window pops up every time and it feels like that should not be the default setting if I have the correct version, and have opened the project in that version many times.

**Comment by Ravbug** [comment]
This should not be happening. It’s supposed to directly open, and only prompt you if it can’t find the editor that’s associated with the project. 

Can you please provide some details about your projects and installs (ie are they on the boot drive, etc)?

**Comment by joonjoonjoon** [comment]
I had manually renamed the folder and I was off by a single digit. Since it was the actual correct unity install inside the folder it didn't prompt any issues and was difficult to spot.
Works as intended now.
