### ISSUE TITLE
Linux AppImage seems to be broken, failing to integrate with AppImageLauncher

### ISSUE THREAD

**Issue by henriquecolini** [Ravbug/UnityHubNative#34]
**Description of the Problem**

The Linux AppImage seems to be broken. I can run it just fine, but there is no icon, and it fails to be integrated to the system with AppImageLauncher. The logs suggest that both the icon and the desktop entry aren't working.

This has been verified to not be an issue with AppImageLauncher, as I've tested other AppImages and they integrate to the system just fine.

**To Reproduce**
1. Download the latest Linux release of [UnityHubNative](https://github.com/Ravbug/UnityHubNative/releases/download/1.53/UnityHubNative-Linux64.zip).
2. Have AppImageLauncher [installed in your system.](https://github.com/TheAssassin/AppImageLauncher/releases/tag/v2.2.0)
3. Unzip and make the UnityHubNative AppImage executable.
4. Run the AppImage, and integrate it to the system.

**Expected behavior**
The AppImage gets integrated to the system as usual.

**Screenshots and/or logs**
![Screenshot from 2023-08-02 17-47-42](https://github.com/Ravbug/UnityHubNative/assets/5795764/0591cfeb-ccdf-4bd2-aecc-9dc39eeb6e94)
![Screenshot from 2023-08-02 17-48-06](https://github.com/Ravbug/UnityHubNative/assets/5795764/8b7fe62f-c474-45b2-b916-cd3022fc661c)

When running from a terminal, we get the following logs:

```
$ ./UnityHubNative.AppImage 
WARNING: No icons found at "usr/share/icons"
WARNING: Using .DirIcon as default app icon
ERROR: Unable to load image.
ERROR: No icon was generated for: /home/henrique/Applications/UnityHubNative_856452fd4606b11d68f9e6b7d15a6679.AppImage
ERROR: appimage_register_in_system : Missing Desktop Entry
Directory '/home/henrique/.local/share/mime/packages' does not exist!
```

**Computer information:**
- OS: Ubuntu 22.04.2 LTS

**Additional context**
Just for comparison, these are the logs when integrating the [draw.io AppImage](https://appimage.github.io/draw.io/) to the system. There is a bunch of other icon extraction logs in here, one for each icon size. I've ommited them for simplicity.

```
Extracting usr/share/icons/hicolor/1024x1024/apps/drawio.png to "/home/henrique/.local/share/icons/hicolor/1024x1024/apps/appimagekit_c316550eb423e6c34d30fe7c366e5806_drawio.png"
WARNING: Unable to resize the application icon into a 128x128 image: "Unable to load image.". It will be written unchanged.
WARNING: Unable to resize the application icon into a 256x256 image: "Unable to load image.". It will be written unchanged.
gtk-update-icon-cache: Cache file created successfully.
Directory '/home/henrique/.local/share/mime/packages' does not exist!
```

**Comment by Ravbug** [comment]
Hi, thanks for the detailed report!

I am not very knowledgeable with AppImage, so I'm not sure how to fix it. 

This is what the inside of the AppImage looks like:
![image](https://github.com/Ravbug/UnityHubNative/assets/22283943/ed63f1ba-68cd-48cb-b609-b12a4ead6070)
`.DirIcon` appears to be a copy of the xpm (somewhat suspicious). This is the contents of `UnityHubNative.desktop` file:

```
[Desktop Entry]
Type=Application
Name=UnityHubNative
Icon=UnityHubNative
Categories=X-None;
```
Do you see anything obviously wrong?

**Comment by henriquecolini** [comment]
Hi! I'm not very knowledgeable with AppImage either, but I did spend a few hours studying your code, the code of some other working AppImages, and that of libappimage itself. I managed to pinpoint the [exact line of code where the error originates from](https://github.com/AppImageCommunity/libappimage/blob/e56c21b5387fde92cbb91c835e7aa16ab60b3879/src/libappimage/utils/resources_extractor/ResourcesExtractor.cpp#L181C1-L182C1), which made me realize the issue was probably with a broken .desktop file.

And, indeed, as it turns out, your .desktop is missing an Exec key:

```Exec=AppRun```

Without this, it's impossible to integrate the app to the system, as it does not know what to actually run. The AppImage itself is still able to run, as it doesn't need the .desktop to run.

This does not fix the missing icons, however. In order to fix that, your AppDir needs to have the icons inside `usr/share/icons`. You can actually have icons of many sizes, and for varying system themes. The default place where the icons are looked up are in `usr/share/icons/<theme>/app/<size>/<appName>`. The standard fallback theme is hicolor and the only available size in this repo is 512x512, so placing the icon in `usr/share/icons/hicolor/app/512x512/UnityHubNative.xmp` fixes the issue.

As not to have duplicates, it's common for the root-level `.DirName` and UnityHubNative.xmp to be symlinks to one of the provided icons.

I'm finishing up a pull request that does these fixes. Hope to publish it in the next hour or so.

While we're at it- what do you think of a new logo? I could help with that as well.

**Comment by henriquecolini** [comment]
The PR (#35) has been made! Works perfectly on my end, but it would not hurt to test on other machines.

**Comment by Ravbug** [comment]
Awesome, thank you so much for your help! I tested it and it appears to work for me as well.

I appreciate your offer to help on a new icon, but at the moment I don't really want to change the current one.

Thanks again!
