### ISSUE TITLE
[BUG] New project overwrites existing project with same name with *no warning*

### ISSUE THREAD

**Issue by videopilot** [Ravbug/UnityHubNative#39]
See video.

Here I have a project named "New Unity Project" and I add a cube to the sample scene and save. Then I go to create a new project in UnityHubNative, leave the name at the default "New Unity Project" and it proceeds to overwrite the existing project with that name with no warning, I assume replacing all files from the template (you can see the sample scene goes from today 12:29 back to Nov 2020 and the added cube is gone).

This is very destructive. There should be a warning about overwriting an existing project.

https://github.com/Ravbug/UnityHubNative/assets/6528746/9cedf4c6-962e-44d0-9e59-cba749f2c690

**Comment by Ravbug** [comment]
Pre-release builds with this issue fixed are available here: https://github.com/Ravbug/UnityHubNative/actions/runs/8009149822/job/21877172740
