### ISSUE TITLE
Unity no longer allows manual activation for personal plans

### ISSUE THREAD

**Issue by Mhowser** [Ravbug/UnityHubNative#42]
https://docs.unity3d.com/Manual/ManualActivationGuide.html

**Comment by Ravbug** [comment]
Thanks for the heads up! Does this retroactively affect previous Unity versions, or only new versions going forward?

**Comment by Mhowser** [comment]
I do not know right now, I'm assuming this is the case for all versions since the website only allows one to manually activate by serial number only.

**Comment by sejef** [comment]
@Ravbug You'd have to rename the panes too ;-) Any hope for a Personal Plan License creation/activation without using the official hub ?

**Comment by Ravbug** [comment]
@sejef That would require reverse-engineering the Unity licensing system. I have no plans to do that but anyone is welcome to open a PR.
