### ISSUE TITLE
Add manual activation

### ISSUE THREAD

**Issue by NeatSketch** [Ravbug/UnityHubNative#7]
Unity has [command line options for manual activation](https://docs.unity3d.com/Manual/ManualActivationGuide.html).
Thus, Unity Hub's manual activation dialog can be easily replicated, which would be great, because Unity Hub would no longer be needed!

![image](https://user-images.githubusercontent.com/8350625/159156211-56aaa73e-6e2b-4901-87c8-0e1b0db07774.png)

**Comment by Ravbug** [comment]
The latest nightly has a beta of this feature: https://github.com/Ravbug/UnityHubNative/actions/runs/3129530563
