### ISSUE TITLE
[BUG]Release 1.42 does not open on Mac,  1.4.1 does open. the zip seems incomplete 

### ISSUE THREAD

**Issue by larssteenhoff** [Ravbug/UnityHubNative#8]
Release 1.42 does not open on Mac,  1.4.1 does open. the zip seems incomplete

**Comment by Ravbug** [comment]
I have uploaded a new Mac build, can you please try it? https://github.com/Ravbug/UnityHubNative/releases/tag/1.42

**Comment by konsnos** [comment]
Hey, I'm a new user and tried it as well and I've got the same issue. Downloaded the new mac build from above. Working on a MacBook Air (M1, 2020).

I've also tried 1.4.1 and I get the same pop-up.

"“Unity Hub Native.app” can’t be opened because Apple cannot check it for malicious software."

**Comment by larssteenhoff** [comment]
> I have uploaded a new Mac build, can you please try it? https://github.com/Ravbug/UnityHubNative/releases/tag/1.42

This one works!  thank you

**Comment by larssteenhoff** [comment]
> 
1.4.2 works:  Right click and press open ( this is a mac security thing )

**Comment by konsnos** [comment]
Thanks @larssteenhoff !
