### ISSUE TITLE
always on search

### ISSUE THREAD

**Issue by laurentopia** [Ravbug/UnityHubNative#9]
with over 50 projects, finding the one is a struggle. always on search was implemented in unity bloat 3.0, that's what's missing here.

**Comment by Ravbug** [comment]
The latest nightly has a beta of this feature: https://github.com/Ravbug/UnityHubNative/actions/runs/3129530563

**Comment by laurentopia** [comment]
very Nice.
It needs to show the list as you type though. 
And with low debounce, 20ms no more. unless list is thousands projects, it should be instant.

**Comment by Ravbug** [comment]
Implemented in 6e075a700523efc91cdf7fb8b53c7e11ed3e4774

**Comment by laurentopia** [comment]
Thank you.
